---  
- name: remove old wapt sources.list
  file: 
    path: "{{ centos_wapt_sources_list }}"
    state: absent

- rpm_key:
    state: present
    key: "{{ centos_gpg_key }}"

- name: adding tis-wapt repository
  yum_repository:
    name: wapt
    description: WAPT Server Repo
    file: wapt
    baseurl: "{{ centos_wapt_source }}"
    gpgcheck: no
    enabled: yes

- name: yum update
  yum:
    name: '*'
    state: latest

- name: "Install postgresql-{{ pgsql_version }}"
  yum:
    name:
    - postgresql96-server
    - postgresql96-contrib
    - cabextract
    state: latest

- name: "install tis-waptserver {{wapt_version}} packages"
  yum:
    name:
    - tis-waptserver
    - tis-waptsetup
    state: latest

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version 

- name: initialize postgresql db
  shell: "sudo {{ postgresql_bin_path }}/postgresql96-setup initdb"
  when: not pgdata_dir_version.stat.exists
  args:
    warn: false

- name: enable WAPT server services
  service: name={{item}} enabled=yes
  with_items:
      - "postgresql-{{ pgsql_version }}"
      - waptserver
      - nginx

- name: start WAPT server services
  service: name={{item}} state=started
  with_items:
      - "postgresql-{{ pgsql_version }}"
      - nginx
      - waptserver

