---
- name: remove old wapt sources.list
  file: 
    path: "{{ debian_wapt_sources_list }}"
    state: absent

- name: flush apt cache
  shell: "rm -rf /var/lib/apt/lists/*"
  args:
    warn: false

- name: apt clean
  apt:
    autoclean: yes

- name: adding gpg key for wapt repo
  apt_key:
    url: "{{ debian_gpg_key }}"

- name: "adding tis-wapt repository for WAPT {{ wapt_version }}"
  apt_repository: 
    repo: "deb {{ debian_wapt_source }} {{ansible_distribution_release}} main"
    state: present
    filename: '{{debian_wapt_sources_list}}'

- name: apt-get update
  apt:
    update_cache: yes

- name: "install tis-waptserver {{wapt_version}} packages"
  apt: 
    pkg:
    - tis-waptserver
    - tis-waptsetup
    state: latest
    update_cache: yes

- name: enable WAPT server services
  service: name={{item}} enabled=yes
  with_items:
      - postgresql
      - waptserver
      - nginx

- name: start WAPT server services
  service: name={{item}} state=started
  with_items:
      - postgresql
      - nginx
      - waptserver

