---
- name: apt-get update
  apt:
    update_cache: yes

- name: apt-get upgrade
  apt:
    name: "*"
    state: latest
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: install waptserver dependencies
  apt: 
    pkg:
    - apt-transport-https      
    - dirmngr
    - nginx
    - dialog
    - python-tz
    - cabextract
    - sudo
    - python-psutil
    - krb5-user
    - msktutil
    - python-pyparsing
    - lsb-release
    - htop
    state: latest
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
