---
- name: apt-get upgrade
  apt:
    name: "*"
    state: latest
    update_cache: yes
  tags: apt_update_upgrade

- name: install waptserver dependencies
  apt:
    pkg: [ 'apt-transport-https', 'dirmngr', 'nginx'
           'dialog', 'python-tz', 'cabextract'
           'sudo', 'python-psutil', 'krb5-user'
           'msktutil', 'python-pyparsing'
           'lsb-release', 'htop', 'aptitude' ]
    state: latest
